apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  params:
    - name: repo-url
      type: string
  workspaces:
    - name: source
  tasks:
    - name: npminstall
      taskRef:
        name: npm-install
      workspaces:
        - name: source
          workspace: source
    - name: tests
      taskRef:
        name: jasmine-tests
      runAfter:
        - npminstall
      workspaces:
        - name: source
          workspace: source
    - name: build
      taskRef:
        name: docker-build
      runAfter:
        - tests
      workspaces:
        - name: source
          workspace: source
